In [1]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import optimizers

In [2]:
X=np.array([[70,85,11],[71,89,18],[50,80,20],[99,20,10],[50,10,10]])
y=np.array([73,82,72,57,34])

In [3]:
model = Sequential()

model.add(Dense(1, input_dim=3, activation='linear'))
sgd = optimizers.SGD(lr=0.00001)
model.compile(optimizer=sgd, loss='mse', metrics=['mse'])

In [5]:
model.fit(X, y, batch_size=1, epochs=2000, verbose=0, shuffle=False)
model.fit(X, y, batch_size=1, epochs=10, shuffle=False)

Epoch 1/10
5/5 [==============================] - 0s 600us/step - loss: 0.0198 - mse: 0.0198  
Epoch 2/10
5/5 [==============================] - 0s 200us/step - loss: 0.0198 - mse: 0.0198  
Epoch 3/10
5/5 [==============================] - 0s 200us/step - loss: 0.0198 - mse: 0.0198  
Epoch 4/10
5/5 [==============================] - 0s 400us/step - loss: 0.0198 - mse: 0.0198  
Epoch 5/10
5/5 [==============================] - 0s 400us/step - loss: 0.0198 - mse: 0.0198  
Epoch 6/10
5/5 [==============================] - 0s 400us/step - loss: 0.0197 - mse: 0.0197  
Epoch 7/10
5/5 [==============================] - 0s 400us/step - loss: 0.0197 - mse: 0.0197  
Epoch 8/10
5/5 [==============================] - 0s 400us/step - loss: 0.0197 - mse: 0.0197  
Epoch 9/10
5/5 [==============================] - 0s 400us/step - loss: 0.0197 - mse: 0.0197  
Epoch 10/10
5/5 [==============================] - 0s 400us/step - loss: 0.0197 - mse: 0.0197  


In [6]:
model.predict(X)

array([[73.02298 ],
       [81.971924],
       [72.01236 ],
       [57.141262],
       [33.73845 ]], dtype=float32)

In [7]:
model.predict([[20, 99, 10], [40, 50, 20]])

array([[57.961628],
       [55.90492 ]], dtype=float32)

In [8]:
X=np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y=np.array([0, 1, 1, 1])

In [9]:
model = Sequential()
model.add(Dense(1, input_dim=2, activation='sigmoid'))
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['binary_accuracy'])

In [10]:
model.fit(X, y, shuffle=False, batch_size=1, epochs=800, verbose=0)
model.fit(X, y, shuffle=False, batch_size=1, epochs=10)

Epoch 1/10
4/4 [==============================] - 0s 500us/step - loss: 0.2169 - binary_accuracy: 1.0000
Epoch 2/10
4/4 [==============================] - 0s 500us/step - loss: 0.2167 - binary_accuracy: 1.0000
Epoch 3/10
4/4 [==============================] - 0s 250us/step - loss: 0.2166 - binary_accuracy: 1.0000
Epoch 4/10
4/4 [==============================] - 0s 250us/step - loss: 0.2164 - binary_accuracy: 1.0000
Epoch 5/10
4/4 [==============================] - 0s 500us/step - loss: 0.2162 - binary_accuracy: 1.0000
Epoch 6/10
4/4 [==============================] - 0s 500us/step - loss: 0.2161 - binary_accuracy: 1.0000
Epoch 7/10
4/4 [==============================] - 0s 250us/step - loss: 0.2159 - binary_accuracy: 1.0000
Epoch 8/10
4/4 [==============================] - 0s 250us/step - loss: 0.2158 - binary_accuracy: 1.0000
Epoch 9/10
4/4 [==============================] - 0s 500us/step - loss: 0.2156 - binary_accuracy: 1.0000
Epoch 10/10
4/4 [==============================] - 0s 2

In [11]:
model.predict(X)

array([[0.4139397 ],
       [0.8590597 ],
       [0.85665476],
       [0.98097855]], dtype=float32)