In [1]:
X, y = zip(['a', 1], ['b', 2], ['c', 3])
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [2]:
sequences=[['a', 1], ['b', 2], ['c', 3]]
X, y = zip(*sequences)
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


# 데이터프레임 이용(pandas)

In [4]:
import pandas as pd

values = [['당신에게 드리는 마지막 혜택!', 1],
         ['내일 뵐 수 있을지 확인 부탁드...', 0],
         ['도연씨, 잘 지내시죠? 오랜만입...', 0],
         ['(광고) AI로 주가를 예측할 수 있다.!', 1]]

columns = ['메일 본문', '스팸 메일 유무']

df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0         당신에게 드리는 마지막 혜택!         1
1     내일 뵐 수 있을지 확인 부탁드...         0
2     도연씨, 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다.!         1

In [5]:
X = df['메일 본문']
y = df['스팸 메일 유무']

In [6]:
print(X)

0           당신에게 드리는 마지막 혜택!
1       내일 뵐 수 있을지 확인 부탁드...
2       도연씨, 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다.!
Name: 메일 본문, dtype: object


# Numpy이용

In [8]:
import numpy as np
ar = np.arange(0, 16).reshape((4,4))
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [9]:
X = ar[:, :3]
print(X)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [13]:
y = ar[:, 3]
print(y)

[ 3  7 11 15]


# 테스트 데이터 분리하기

In [15]:
from sklearn.model_selection import train_test_split
# train_test_split : (독립 변수, 종속 변수, 테스트용 데이터 갯수(1보다 작은 실수일 경우 비율), 학습용 데이터 갯수, 난수 시드)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

In [18]:
import numpy as np

from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
print(X)
print(list(y))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1234)

In [20]:
print(X_train)
print(X_test)

[[2 3]
 [4 5]
 [6 7]]
[[8 9]
 [0 1]]


In [21]:
print(y_train)
print(y_test)

[1, 2, 3]
[4, 0]
