In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

### low-level

In [5]:
z = torch.FloatTensor([1, 2, 3])

In [6]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [7]:
hypothesis.sum()

tensor(1.)

In [8]:
z = torch.rand(3, 5, requires_grad = True)

In [9]:
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward>)


In [10]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([0, 2, 1])


In [13]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [16]:
print(y.unsqueeze(1))

tensor([[0],
        [2],
        [1]])


In [17]:
# 비용함수
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.4689, grad_fn=<MeanBackward0>)


### high-level

In [18]:
# F.softmax() + torch.log() = F.log_softmax()
F.log_softmax(z, dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward>)

In [20]:
# 비용함수
# F.log_softmax() + F.nll_loss() = F.cross_entropy()
F.cross_entropy(z, y)

tensor(1.4689, grad_fn=<NllLossBackward>)