## 2D Tensor
|t| = (Batch size, dim)(행의 크기, 열의 크기)

## 3D Tensor
- 비전분야
|t| = (Batch size, width, height)(세로, 가로, 높이)

- NLP분야
|t| = (Batch size, length, dim)(batch size, 문장 길이, 단어 벡터의 차원)

# 넘파이로 텐서 만들기

In [8]:
import numpy as np

In [9]:
# 1차원 벡터
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [10]:
print('Rank of t: ',t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


# 파이토치 텐서 선언

In [11]:
import torch

In [12]:
# 1차원 백터 만들기
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [13]:
print(t.dim()) # dim : 텐서의 차원
print(t.shape) # shape : 텐서의 크기
print(t.size()) # size : 텐서의 크기

1
torch.Size([7])
torch.Size([7])


In [14]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [15]:
# 2차원 벡터 만들기
t = torch.FloatTensor([[1., 2., 3.],
                      [4., 5., 6.],
                      [7., 8., 9.],
                      [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [16]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


## 브로드캐스팅 
- 크기가 다른 텐서에 대해 크기를 자동으로 맞춰 연산을 수행하게 만드는 기능

In [17]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [18]:
m1 = torch.FloatTensor([1, 2])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([4., 5.])


In [19]:
m1 = torch.FloatTensor([1, 2])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## 행렬 곱셈과 곱셈의 차이

In [20]:
# 행렬 곱셈 : matmul
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1:', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [21]:
# 원소 곱셈 : mul or *
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) 
print('Shape of Matrix 2: ', m2.shape) #
print(m1 * m2) 
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## View(뷰)
- 원소의 수를 유지하면서 텐서의 크기 변경
- numpy의 reshape과 동일

In [22]:
# 3차원 -> 2차원
t = np.array([[[0, 1, 2],
             [3, 4, 5]],
            [[6, 7, 8],
            [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [23]:
print(ft.shape)

torch.Size([2, 2, 3])


view[-1, 3] : -1 은 첫번째 차원은 사용자가 잘 모르니 파이토치에게 맡기고 3은 두번째 차원의 길이는 3으로 설정

In [24]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [25]:
# 3차원 텐서는 유지하되, 크기만 변경
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [26]:
# squeeze : 1인 차원을 제거
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [28]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [29]:
# unsqueeze : 1인 차원을 추가
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [30]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


## 타입 캐스팅

In [31]:
# long타입의 텐서
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [32]:
# .float()를 붙이면 float형 타입으로 변경
print(lt.float())

tensor([1., 2., 3., 4.])


In [33]:
# Byte타입의 텐서
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [34]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## 연결

In [35]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [36]:
# cat : 텐서를 연결
print(torch.cat([x, y], dim=0)) # dim=0 : 첫번째 차원을 늘리라는 의미

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [37]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## 스택킹
- 연결하는 다른 방법

In [38]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [39]:
# stack : 연결
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## ones_like / zeros_like 
- pandas의 ones / zeros와 동일

In [40]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [41]:
print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [42]:
print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place operation(덮어쓰기)
- 연산 뒤에 _ 를 붙이면 기존의 값을 덮어쓰기 한다.

In [43]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [44]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [45]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
